### ISSUE TITLE
Unrecognized Recipe Type Log Spam

### ISSUE THREAD

**Issue by milkev** [teamauroramods/EnhancedMushrooms-Fabric#19]
Various unrecognized recipe types such as 'environmental:sawing' and 'farmersdelight:cooking'

environmental is forge only, and the recipes shouldnt be on the fabric version at all.

i hear that disabling json files is a quite involved process, but if you know where to look/learn it would be nice if only to save the headache of trying to look through a ton of error messages for the one that actually means something, since there are quite a few error messages spat out by this mod.

[Pastebin of Relevant Log](https://pastebin.com/NLJ54XJj)

**Comment by JustinPlayzz** [comment]
We might have forgotten to remove some forge recipes @StevePlayzz can you fix this?

**Comment by Steven-Baez** [comment]
yes tomorrow I can

**Comment by Yucked** [comment]
Any update on this?
```
[21:23:47] [Worker-Main-14/ERROR]: Parsing error loading recipe enhanced_mushrooms:cutting/brown_mushroom_sign
com.google.gson.JsonParseException: An ingredient entry needs either a tag or an item
        at net.minecraft.class_1856.method_8107(class_1856.java:167) ~[intermediary-server.jar:?]
        at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[intermediary-server.jar:?]
        at com.nhoryzon.mc.farmersdelight.recipe.CuttingBoardRecipeSerializer.read(CuttingBoardRecipeSerializer.java:45) ~[farmers-delight-fabric-1.17.1-0.1.3.jar:?]
        at com.nhoryzon.mc.farmersdelight.recipe.CuttingBoardRecipeSerializer.method_8121(CuttingBoardRecipeSerializer.java:15) ~[farmers-delight-fabric-1.17.1-0.1.3.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[21:23:47] [Worker-Main-14/ERROR]: Parsing error loading recipe enhanced_mushrooms:cutting/brown_mushroom_hyphae
com.google.gson.JsonParseException: An ingredient entry needs either a tag or an item
        at net.minecraft.class_1856.method_8107(class_1856.java:167) ~[intermediary-server.jar:?]
        at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[intermediary-server.jar:?]
        at com.nhoryzon.mc.farmersdelight.recipe.CuttingBoardRecipeSerializer.read(CuttingBoardRecipeSerializer.java:45) ~[farmers-delight-fabric-1.17.1-0.1.3.jar:?]
        at com.nhoryzon.mc.farmersdelight.recipe.CuttingBoardRecipeSerializer.method_8121(CuttingBoardRecipeSerializer.java:15) ~[farmers-delight-fabric-1.17.1-0.1.3.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[21:23:47] [Worker-Main-14/ERROR]: Parsing error loading recipe enhanced_mushrooms:cutting/red_mushroom_hyphae
com.google.gson.JsonParseException: An ingredient entry needs either a tag or an item
        at net.minecraft.class_1856.method_8107(class_1856.java:167) ~[intermediary-server.jar:?]
        at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[intermediary-server.jar:?]
        at com.nhoryzon.mc.farmersdelight.recipe.CuttingBoardRecipeSerializer.read(CuttingBoardRecipeSerializer.java:45) ~[farmers-delight-fabric-1.17.1-0.1.3.jar:?]
        at com.nhoryzon.mc.farmersdelight.recipe.CuttingBoardRecipeSerializer.method_8121(CuttingBoardRecipeSerializer.java:15) ~[farmers-delight-fabric-1.17.1-0.1.3.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[21:23:47] [Worker-Main-14/ERROR]: Parsing error loading recipe enhanced_mushrooms:cutting/brown_mushroom_door
com.google.gson.JsonParseException: An ingredient entry needs either a tag or an item
        at net.minecraft.class_1856.method_8107(class_1856.java:167) ~[intermediary-server.jar:?]
        at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[intermediary-server.jar:?]
        at com.nhoryzon.mc.farmersdelight.recipe.CuttingBoardRecipeSerializer.read(CuttingBoardRecipeSerializer.java:45) ~[farmers-delight-fabric-1.17.1-0.1.3.jar:?]
        at com.nhoryzon.mc.farmersdelight.recipe.CuttingBoardRecipeSerializer.method_8121(CuttingBoardRecipeSerializer.java:15) ~[farmers-delight-fabric-1.17.1-0.1.3.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[21:23:47] [Worker-Main-14/ERROR]: Parsing error loading recipe enhanced_mushrooms:cutting/red_mushroom_stem
com.google.gson.JsonParseException: An ingredient entry needs either a tag or an item
        at net.minecraft.class_1856.method_8107(class_1856.java:167) ~[intermediary-server.jar:?]
        at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[intermediary-server.jar:?]
        at com.nhoryzon.mc.farmersdelight.recipe.CuttingBoardRecipeSerializer.read(CuttingBoardRecipeSerializer.java:45) ~[farmers-delight-fabric-1.17.1-0.1.3.jar:?]
        at com.nhoryzon.mc.farmersdelight.recipe.CuttingBoardRecipeSerializer.method_8121(CuttingBoardRecipeSerializer.java:15) ~[farmers-delight-fabric-1.17.1-0.1.3.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[21:23:47] [Worker-Main-14/ERROR]: Parsing error loading recipe enhanced_mushrooms:cutting/red_mushroom_trapdoor
com.google.gson.JsonParseException: An ingredient entry needs either a tag or an item
        at net.minecraft.class_1856.method_8107(class_1856.java:167) ~[intermediary-server.jar:?]
        at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[intermediary-server.jar:?]
        at com.nhoryzon.mc.farmersdelight.recipe.CuttingBoardRecipeSerializer.read(CuttingBoardRecipeSerializer.java:45) ~[farmers-delight-fabric-1.17.1-0.1.3.jar:?]
        at com.nhoryzon.mc.farmersdelight.recipe.CuttingBoardRecipeSerializer.method_8121(CuttingBoardRecipeSerializer.java:15) ~[farmers-delight-fabric-1.17.1-0.1.3.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[21:23:47] [Worker-Main-14/ERROR]: Parsing error loading recipe enhanced_mushrooms:cutting/brown_mushroom_stem
com.google.gson.JsonParseException: An ingredient entry needs either a tag or an item
        at net.minecraft.class_1856.method_8107(class_1856.java:167) ~[intermediary-server.jar:?]
        at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[intermediary-server.jar:?]
        at com.nhoryzon.mc.farmersdelight.recipe.CuttingBoardRecipeSerializer.read(CuttingBoardRecipeSerializer.java:45) ~[farmers-delight-fabric-1.17.1-0.1.3.jar:?]
        at com.nhoryzon.mc.farmersdelight.recipe.CuttingBoardRecipeSerializer.method_8121(CuttingBoardRecipeSerializer.java:15) ~[farmers-delight-fabric-1.17.1-0.1.3.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[21:23:47] [Worker-Main-14/ERROR]: Parsing error loading recipe enhanced_mushrooms:cutting/red_mushroom_door
com.google.gson.JsonParseException: An ingredient entry needs either a tag or an item
        at net.minecraft.class_1856.method_8107(class_1856.java:167) ~[intermediary-server.jar:?]
        at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[intermediary-server.jar:?]
        at com.nhoryzon.mc.farmersdelight.recipe.CuttingBoardRecipeSerializer.read(CuttingBoardRecipeSerializer.java:45) ~[farmers-delight-fabric-1.17.1-0.1.3.jar:?]
        at com.nhoryzon.mc.farmersdelight.recipe.CuttingBoardRecipeSerializer.method_8121(CuttingBoardRecipeSerializer.java:15) ~[farmers-delight-fabric-1.17.1-0.1.3.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
com.google.gson.JsonParseException: An ingredient entry needs either a tag or an itemtting/brown_mushroom_trapdoor
        at net.minecraft.class_1856.method_8107(class_1856.java:167) ~[intermediary-server.jar:?]
        at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[intermediary-server.jar:?]
        at com.nhoryzon.mc.farmersdelight.recipe.CuttingBoardRecipeSerializer.read(CuttingBoardRecipeSerializer.java:45) ~[farmers-delight-fabric-1.17.1-0.1.3.jar:?]
        at com.nhoryzon.mc.farmersdelight.recipe.CuttingBoardRecipeSerializer.method_8121(CuttingBoardRecipeSerializer.java:15) ~[farmers-delight-fabric-1.17.1-0.1.3.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[21:23:47] [Worker-Main-14/ERROR]: Parsing error loading recipe enhanced_mushrooms:cutting/red_mushroom_sign
com.google.gson.JsonParseException: An ingredient entry needs either a tag or an item
        at net.minecraft.class_1856.method_8107(class_1856.java:167) ~[intermediary-server.jar:?]
        at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[intermediary-server.jar:?]
        at com.nhoryzon.mc.farmersdelight.recipe.CuttingBoardRecipeSerializer.read(CuttingBoardRecipeSerializer.java:45) ~[farmers-delight-fabric-1.17.1-0.1.3.jar:?]
        at com.nhoryzon.mc.farmersdelight.recipe.CuttingBoardRecipeSerializer.method_8121(CuttingBoardRecipeSerializer.java:15) ~[farmers-delight-fabric-1.17.1-0.1.3.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
```

**Comment by Steven-Baez** [comment]
should be fixed in the new repo https://github.com/teamauroramods/EnhancedMushrooms
